import { GOOGLE_MAP_API_KEY, SENTRY_URL, STAGING_URL } from '@env';

const BASE_URL = STAGING_URL;
// const BASE_URL = process.env.NODE_ENV === 'production' ? LIVE_URL : DEV_URL;
// const BASE_URL = process.env.NODE_ENV === 'production' ? DEV_URL : DEV_URL;

export const ApiConstants = {
  BASE_URL,
  SENTRY_URL,
  GOOGLE_MAP_API_KEY,
  SEND_AUTH_OTP: `${BASE_URL}login/send_otp`,

  VERIFY_AUTH_OTP: `${BASE_URL}login/verify_otp`,
  REGISTER: `${BASE_URL}registers`,
  ROLES: `${BASE_URL}role_list`,
  REQUIREMENT_LIST: `${BASE_URL}requirment_list`,
  COUNTRY_STATE: `${BASE_URL}country_state`,
  DEALER_COMPANY: `${BASE_URL}main_categories`,
  HIDE_PROFILE_IN_DIRECTORY: `${BASE_URL}hide_profile_in_directory`,
  ADD_REVIEW: `${BASE_URL}review/add`,
  LOGOUT: `${BASE_URL}logout`,

  COUNTRIES: `${BASE_URL}country_list`,
  STATES: `${BASE_URL}states_list?id_country=`,
  CITY: `${BASE_URL}cities_list?id_state=`,
  CATEGORY: `${BASE_URL}category_list`,
  SUB_CATEGORY: `${BASE_URL}sub_category_list`,
  GET_MODEL: `${BASE_URL}model_list`,
  GET_TYPE_OF_MANUFACTURER: `${BASE_URL}manufacturer_list`,
  GET_PARTS: `${BASE_URL}parts_list`,
  ADD_BUYER_REQUIREMENT: `${BASE_URL}buyer_requirment/saves`,
  ADD_SELLER_REQUIREMENT: `${BASE_URL}seller_details/saves`,
  EDIT_REQUIREMENT: `${BASE_URL}buyer_requirment/update_post`,
  DELETE_REQUIREMENT_IMAGE: `${BASE_URL}buyer_requirment/delete_image_post`,
  DELETE_REQUIREMENT: `${BASE_URL}buyer_requirment/delete_post`,
  DASHBOARD_GET: `${BASE_URL}get_home_data`,
  ADD_ADVERTISEMENT: `${BASE_URL}advertisement/saves`,
  GET_BUYER_REQUIREMENTS: `${BASE_URL}buyer_requirment`,
  GET_BUYER_REQUIREMENTS_DETAIL: `${BASE_URL}buyer_requirment/get_by_id`,
  GET_BUYER_RELATED_POSTS: `${BASE_URL}buyer_requirment/get_related_post`,
  GET_SELLER_REQUIREMENTS: `${BASE_URL}seller_details`,
  GET_SELLER_REQUIREMENTS_DETAIL: `${BASE_URL}seller_details/get_by_id`,
  GET_SELLER_RELATED_POSTS: `${BASE_URL}seller_details/get_related_post`,
  GET_SELLER_POSTS_BY_ID: `${BASE_URL}seller_details/post_by_user_id`,
  GET_CATALOGUES_BY_ID: `${BASE_URL}seller_details/get_catalogue_userwise`,
  ADD_CATALOGUE_FAV: `${BASE_URL}seller_requirment/catalouge_like_unlike`,
  GET_FILTER: `${BASE_URL}get_filter_data`,
  GET_BUYER_LIKE_POST: `${BASE_URL}buyer_requirment/buyer_like_unlike`,
  GET_SELLER_LIKE_POST: `${BASE_URL}seller_requirment/seller_like_unlike`,
  GET_BUYER_REQUIREMENTS_BY_ID: `${BASE_URL}buyer_requirment/requirment_post_by_user_id_post`,
  GET_FAV_POSTS: `${BASE_URL}fav/get_by_type`,

  GET_PROFILE: `${BASE_URL}profile`,
  EDIT_PERSONAL_PROFILE: `${BASE_URL}update_profile`,
  UPDATE_BUSINESS_PROFILE: `${BASE_URL}update_profile_business`,
  UPDATE_BUSINESS_SPECIFIC_FIELDS: `${BASE_URL}update_business_specific_fields`,
  UPDATE_SPECIFIC_FIELDS: `${BASE_URL}update_profile_specific_fields`,
  BUSINESS_SHOP_REMOVE: `${BASE_URL}remove_business_shop_image_by_id`,
  COMPANY_PDF_REMOVE: `${BASE_URL}delete_business_company_pdf`,
  COMPANY_PDF_UPDATE: `${BASE_URL}update_business_company_pdf`,
  GET_TERMS: `${BASE_URL}terms`,
  GET_PRIVACY: `${BASE_URL}privacy`,
  GET_FAQ: `${BASE_URL}faq_list`,
  CONTACT_US: `${BASE_URL}contactus/saves`,
  DELETE_ACCOUNT: `${BASE_URL}contactus/delete_account_request`,
  GET_SELLER_PROFILE: `${BASE_URL}profile`,
  ADD_CATALOGUES: `${BASE_URL}seller_details/catalogue_add`,

  GET_DIRECTORY: `${BASE_URL}directory`,
  GET_DIRECTORY_DETAIL: `${BASE_URL}directory/get_by_id`,

  ADD_SHORTS: `${BASE_URL}shorts/add`,
  GET_SHORTS: `${BASE_URL}shorts/all_shorts_lists`,
  LIKE_UNLIKE_SHORTS: `${BASE_URL}shorts/shorts_like_unlike`,
  DELETE_SHORT: `${BASE_URL}shorts/delete_video_by_id`,
  ADD_REPLY_COMMENT: `${BASE_URL}shorts/add_comments_and_reply`,
  GET_REPLY_COMMENT: `${BASE_URL}shorts/get_shorts_by_video_id`,

  ADD_GALLERY: `${BASE_URL}add_business_shop_image_video`,
  GET_GALLERY: `${BASE_URL}get_business_image_video_list`,
  DELETE_GALLERY: `${BASE_URL}remove_business_shop_image_video`,

  ADD_COMPANY_PDF: `${BASE_URL}add_business_pdf_and_names`,
  GET_COMPANY_PDF: `${BASE_URL}get_business_pdf_and_names`,
  DELETE_COMPANY_PDF: `${BASE_URL}delete_business_pdf_and_names`,

  GET_NOTIFICATION: `${BASE_URL}notification/get_all`,
  DELETE_NOTIFICATION: `${BASE_URL}notification/delete`,
  MARK_ALL_READ: `${BASE_URL}notification/mark_all_read`,
  MARK_INDIVIDUAL_READ: `${BASE_URL}notification/mark_read_by_id`,
  UNREAD_COUNT: `${BASE_URL}notification/unread_count`,
  UPDATE_PUSH_TOKEN: `${BASE_URL}notification/update_fcm_token`,
  SEND_CHAT_NOTIFICATIONS: `${BASE_URL}notification/send_chat_notification`,
};
